name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_in_container:
    runs-on: ubuntu-latest
    container: wormholestudio/move-cli:latest
    permissions: 
      contents: read
      packages: write 
    steps:

      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          branch: main
          name: dist
          path: quark
          repo: WormholeStudio/quark
      - run:  move functional-test 
      - run: move publish 
      # - run: java -jar quark/quark.jar
