name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - 
        uses: docker://wormholestudio/move-cli:latest
      - uses: actions/checkout@v2
      - run: ls && pwd && move
      - uses: ./.github/actions/action.yaml

