name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container:
    container: docker://wormholestudio/move-cli:latest
    permissions: 
      contents: read
      packages: write 
    steps:

      - run: ls /
      - run: echo $HOME
      
#       - uses: actions/checkout@v2
#       - 
#         uses: docker://wormholestudio/move-cli:latest
      - uses: actions/checkout@v2
      - run: ls && pwd && move
      - uses: ./.github/actions/action.yaml

