name: release move cli
on:
  push:
    branches:
      - main

jobs:
  build-linux-release:
    name: build move cli on linux platform
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          repository: 'starcoinorg/starcoin'
          ref: 'master'
          path: 'starcoin'
          fetch-depth: 5

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: build move cli
        working-directory: starcoin
        run: cargo build --package move-cli --release

      - name: zip move cli
        run: |
          cp starcoin/target/release/move .
          zip move.zip move

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Daily release of move-cli
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: move.zip
          asset_name: move.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
